import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import MainMenu from "@/ui/MainMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=" flex flex-col items-center relative">
          <MainMenu />
          <div className=" w-[90%] absolute top-20  md:right-5 mx-auto">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
